// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/quiz_attemp.dart';
import 'models/table_overall_stats.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4165570517916600519),
    name: 'QuizAttemp',
    lastPropertyId: const obx_int.IdUid(6, 9122534839994369263),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4876238966227809832),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6909058053986422622),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4312291191362885146),
        name: 'tableNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8324536110113187326),
        name: 'correctAnswers',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7312094887810469062),
        name: 'totalQuestions',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9122534839994369263),
        name: 'durationInSeconds',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7922726385351882690),
    name: 'TableOverallStats',
    lastPropertyId: const obx_int.IdUid(8, 1725148359479206162),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1822466487713846490),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6911105050596604463),
        name: 'tableNumber',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 3755971674110176557),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2819264881433091199),
        name: 'totalAttempts',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4149257674861590095),
        name: 'totalCorrectAnswersSum',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8990777041937248253),
        name: 'totalQuestionsSum',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3862316502265845973),
        name: 'bestTimeInSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6734904607425124203),
        name: 'bestScoreCorrect',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1725148359479206162),
        name: 'bestScoreTotal',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7922726385351882690),
    lastIndexId: const obx_int.IdUid(1, 3755971674110176557),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    QuizAttemp: obx_int.EntityDefinition<QuizAttemp>(
      model: _entities[0],
      toOneRelations: (QuizAttemp object) => [],
      toManyRelations: (QuizAttemp object) => {},
      getId: (QuizAttemp object) => object.id,
      setId: (QuizAttemp object, int id) {
        object.id = id;
      },
      objectToFB: (QuizAttemp object, fb.Builder fbb) {
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.timestamp.millisecondsSinceEpoch);
        fbb.addInt64(2, object.tableNumber);
        fbb.addInt64(3, object.correctAnswers);
        fbb.addInt64(4, object.totalQuestions);
        fbb.addInt64(5, object.durationInSeconds);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final tableNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final correctAnswersParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final totalQuestionsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final durationInSecondsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object = QuizAttemp(
          id: idParam,
          timestamp: timestampParam,
          tableNumber: tableNumberParam,
          correctAnswers: correctAnswersParam,
          totalQuestions: totalQuestionsParam,
          durationInSeconds: durationInSecondsParam,
        );

        return object;
      },
    ),
    TableOverallStats: obx_int.EntityDefinition<TableOverallStats>(
      model: _entities[1],
      toOneRelations: (TableOverallStats object) => [],
      toManyRelations: (TableOverallStats object) => {},
      getId: (TableOverallStats object) => object.id,
      setId: (TableOverallStats object, int id) {
        object.id = id;
      },
      objectToFB: (TableOverallStats object, fb.Builder fbb) {
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.tableNumber);
        fbb.addInt64(2, object.totalAttempts);
        fbb.addInt64(3, object.totalCorrectAnswersSum);
        fbb.addInt64(4, object.totalQuestionsSum);
        fbb.addInt64(5, object.bestTimeInSeconds);
        fbb.addInt64(6, object.bestScoreCorrect);
        fbb.addInt64(7, object.bestScoreTotal);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final tableNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final totalAttemptsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final totalCorrectAnswersSumParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final totalQuestionsSumParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final bestTimeInSecondsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final bestScoreCorrectParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final bestScoreTotalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = TableOverallStats(
          id: idParam,
          tableNumber: tableNumberParam,
          totalAttempts: totalAttemptsParam,
          totalCorrectAnswersSum: totalCorrectAnswersSumParam,
          totalQuestionsSum: totalQuestionsSumParam,
          bestTimeInSeconds: bestTimeInSecondsParam,
          bestScoreCorrect: bestScoreCorrectParam,
          bestScoreTotal: bestScoreTotalParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [QuizAttemp] entity fields to define ObjectBox queries.
class QuizAttemp_ {
  /// See [QuizAttemp.id].
  static final id = obx.QueryIntegerProperty<QuizAttemp>(
    _entities[0].properties[0],
  );

  /// See [QuizAttemp.timestamp].
  static final timestamp = obx.QueryDateProperty<QuizAttemp>(
    _entities[0].properties[1],
  );

  /// See [QuizAttemp.tableNumber].
  static final tableNumber = obx.QueryIntegerProperty<QuizAttemp>(
    _entities[0].properties[2],
  );

  /// See [QuizAttemp.correctAnswers].
  static final correctAnswers = obx.QueryIntegerProperty<QuizAttemp>(
    _entities[0].properties[3],
  );

  /// See [QuizAttemp.totalQuestions].
  static final totalQuestions = obx.QueryIntegerProperty<QuizAttemp>(
    _entities[0].properties[4],
  );

  /// See [QuizAttemp.durationInSeconds].
  static final durationInSeconds = obx.QueryIntegerProperty<QuizAttemp>(
    _entities[0].properties[5],
  );
}

/// [TableOverallStats] entity fields to define ObjectBox queries.
class TableOverallStats_ {
  /// See [TableOverallStats.id].
  static final id = obx.QueryIntegerProperty<TableOverallStats>(
    _entities[1].properties[0],
  );

  /// See [TableOverallStats.tableNumber].
  static final tableNumber = obx.QueryIntegerProperty<TableOverallStats>(
    _entities[1].properties[1],
  );

  /// See [TableOverallStats.totalAttempts].
  static final totalAttempts = obx.QueryIntegerProperty<TableOverallStats>(
    _entities[1].properties[2],
  );

  /// See [TableOverallStats.totalCorrectAnswersSum].
  static final totalCorrectAnswersSum =
      obx.QueryIntegerProperty<TableOverallStats>(_entities[1].properties[3]);

  /// See [TableOverallStats.totalQuestionsSum].
  static final totalQuestionsSum = obx.QueryIntegerProperty<TableOverallStats>(
    _entities[1].properties[4],
  );

  /// See [TableOverallStats.bestTimeInSeconds].
  static final bestTimeInSeconds = obx.QueryIntegerProperty<TableOverallStats>(
    _entities[1].properties[5],
  );

  /// See [TableOverallStats.bestScoreCorrect].
  static final bestScoreCorrect = obx.QueryIntegerProperty<TableOverallStats>(
    _entities[1].properties[6],
  );

  /// See [TableOverallStats.bestScoreTotal].
  static final bestScoreTotal = obx.QueryIntegerProperty<TableOverallStats>(
    _entities[1].properties[7],
  );
}
